# Generated by Django 2.2.17 on 2020-11-17 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empressa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empressa', models.CharField(max_length=2000)),
                ('endereco', models.CharField(max_length=2000)),
                ('mail', models.CharField(max_length=2000)),
                ('contato', models.CharField(max_length=2000)),
                ('avalicao', models.IntegerField(default=0, max_length=5)),
            ],
        ),
    ]
