# Generated by Django 2.2.17 on 2020-11-19 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empressa_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empressa',
            name='avalicao',
            field=models.IntegerField(default=0),
        ),
    ]
