# Generated by Django 2.2.17 on 2020-11-19 22:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('empressa_api', '0002_auto_20201119_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='empressa',
            name='numero',
            field=models.CharField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
    ]
